create database customer_behaviour;
use customer_behaviour;
show tables;
select * from customer_shopping_behaviour;
select * from customer_shopping_behaviour;

/*total revenue generated by male vs female customers?*/
select `gender`, sum(`purchase_amount_(usd)`) as revenue
from `customer_shopping_behaviour`
group by `gender`;

/* which customers used discount but still spent more than the average purchase amount*/
select `customer_id`,`purchase_amount_(usd)`
from `customer_shopping_behaviour`
where `discount_applied`="Yes" and `purchase_amount_(usd)`>= (select avg(`purchase_amount_(usd)`) from `customer_shopping_behaviour`);

/*top 5 products with the highest average review rating*/
select `item_purchased`, round(avg(`review_rating`),2) as average_revenue_rating
from `customer_shopping_behaviour`
group by `item_purchased`
order by avg(`review_rating`) desc
limit 5;

/*compare the average purchase amounts between standard and the express shipings*/
select `shipping_type`,avg(`purchase_amount_(usd)`)
from `customer_shopping_behaviour`
where `shipping_type` in ('Standard','Express')
group by `shipping_type`;

/*do subscribed customers spend more? compare average spend and the total revenue between subscribers and non subscribers */
select `subscription_status`,
count(`customer_id`) as total_customers,
round(avg(`purchase_amount_(usd)`),2) as average_spend,
round(sum(`purchase_amount_(usd)`),2) as total_revenue
from `customer_shopping_behaviour`
group by `subscription_status`
order by average_spend, total_revenue desc;

/*which 5 products have the highest percentage of purchases with discounts applied*/
select `item_purchased`,
round(sum(case when `discount_applied`='Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from `customer_shopping_behaviour`
group by `item_purchased`
order by `discount_rate`desc
limit 5;

/*segment customers into new,returning and loyal based on their total no of prev purchases and show the count of each segment*/
with `customer_type` as(
select `customer_id`, `previous_purchases`,
case
when `previous_purchases` = 1 then 'New'
when `previous_purchases` between 2 and 10 then 'Returning'
else 'Loyal'
end as `customer_segment`
from `customer_shopping_behaviour`
)
select `customer_segment`,count(*) as no_of_customers
from `customer_type`
group by `customer_segment`;

/*top 3 most purchased products within each category*/
with `item_counts` as(
select `category`,
`item_purchased`,
count(`customer_id`) as `total_orders`,
Row_Number() over(partition by `category` order by count(`customer_id`)desc) as `item_rank`
from `customer_shopping_behaviour`
group by `category`,`item_purchased`
)
select `item_rank`, `category`,`total_orders`, `item_purchased`
from `item_counts`
where `item_rank` <= 3;

/*are customers who are repeat buyers(purchased more than 5 times) are likely to suabscribe? */
select `subscription_status`,
count(`customer_id`) as repeat_buyers
from `customer_shopping_behaviour`
where `previous_purchases` > 5
group by `subscription_status`;

/*what is the revenue contribution of each age group*/
select `age_group`,
sum(`purchase_amount_(usd)`) as total_revenue
from `customer_shopping_behaviour`
group by `age_group`
order by total_revenue desc;









